# Generated by Django 5.2.7 on 2026-01-18 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('duration', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed,', 'Failed')], default='processing', max_length=20)),
                ('s3_video_key', models.CharField(blank=True, max_length=500, null=True)),
                ('s3_thumbnail_key', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscodingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_file', models.CharField(max_length=500)),
                ('output_file', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcoding_jobs', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_duration', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='videos.video')),
            ],
            options={
                'ordering': ['-last_watched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['course', 'order'], name='videos_vide_course__5d4bed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('video', 'student')},
        ),
    ]
