# Generated by Django 5.2.7 on 2026-01-21 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_coursereferral_courserating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_content', models.TextField(help_text='The text/notes to convert to animation')),
                ('animation_style', models.CharField(choices=[('mathematical', 'Mathematical'), ('business', 'Business'), ('technical', 'Technical'), ('educational', 'Educational')], default='educational', max_length=20)),
                ('duration', models.IntegerField(default=60, help_text='Duration in seconds')),
                ('quality', models.CharField(choices=[('low', 'Low (480p)'), ('medium', 'Medium (720p)'), ('high', 'High (1080p)')], default='medium', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('generated_video', models.FileField(blank=True, null=True, upload_to='generated_videos/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_generations', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='video_gener_status_513970_idx'), models.Index(fields=['instructor', '-created_at'], name='video_gener_instruc_6965f8_idx')],
            },
        ),
    ]
