# Generated by Django 5.2.7 on 2026-01-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_mobile_number_customuser_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase unique identifier for phone auth', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode'), ('gaming', 'Gaming Theme'), ('transparent', 'Transparent Glass'), ('pink', 'Pink Paradise'), ('purple', 'Purple Passion'), ('ocean', 'Ocean Blue'), ('forest', 'Forest Green'), ('sunset', 'Sunset'), ('midnight', 'Midnight Blue')], default='dark', help_text='User preferred theme', max_length=20),
        ),
    ]
