# Generated by Django 5.2.7 on 2026-01-19 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_status_courseresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If private, only enrolled students can access'),
        ),
        migrations.AddField(
            model_name='course',
            name='made_private_at',
            field=models.DateTimeField(blank=True, help_text='When course was last made private', null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_private'], name='courses_cou_is_priv_86864e_idx'),
        ),
    ]
